parameters:
#    kruno_todo.example.class: Kruno\Bundle\TodoBundle\Example

services:
#    kruno_todo.example:
#        class: %kruno_todo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
